-- =====================================================
-- AUDIT FIXES: Storage Buckets and Policies
-- =====================================================
-- Generated by Supabase Audit System
-- Apply these fixes based on audit findings

-- Note: Storage buckets and policies are typically created via Supabase Dashboard
-- or using the Supabase CLI. This file provides the SQL equivalents for reference.

-- =====================================================
-- 1. CREATE MISSING STORAGE BUCKETS
-- =====================================================

-- Create storage buckets (if they don't exist)
-- These commands should be run in the Supabase Dashboard SQL Editor
-- or via the Supabase CLI

/*
-- Landing assets bucket (for public website images)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'landing-assets',
    'landing-assets',
    true,
    10485760, -- 10MB limit
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
) ON CONFLICT (id) DO NOTHING;

-- Branding assets bucket (for logos, etc.)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'branding-assets',
    'branding-assets',
    true,
    5242880, -- 5MB limit
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml']
) ON CONFLICT (id) DO NOTHING;

-- Attachments bucket (for private files)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'attachments',
    'attachments',
    false,
    52428800, -- 50MB limit
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf', 'text/plain']
) ON CONFLICT (id) DO NOTHING;

-- Patient images bucket (for pet photos)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'patient-images',
    'patient-images',
    false,
    10485760, -- 10MB limit
    ARRAY['image/jpeg', 'image/png', 'image/webp']
) ON CONFLICT (id) DO NOTHING;
*/

-- =====================================================
-- 2. STORAGE POLICIES FOR PUBLIC BUCKETS
-- =====================================================

-- Landing assets policies (public read, admin write)
CREATE POLICY "landing_assets_public_read"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'landing-assets');

CREATE POLICY "landing_assets_admin_write"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'landing-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "landing_assets_admin_update"
ON storage.objects FOR UPDATE
TO authenticated
USING (
    bucket_id = 'landing-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "landing_assets_admin_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (
    bucket_id = 'landing-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin'
);

-- Branding assets policies (public read, admin write)
CREATE POLICY "branding_assets_public_read"
ON storage.objects FOR SELECT
TO anon, authenticated
USING (bucket_id = 'branding-assets');

CREATE POLICY "branding_assets_admin_write"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'branding-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "branding_assets_admin_update"
ON storage.objects FOR UPDATE
TO authenticated
USING (
    bucket_id = 'branding-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "branding_assets_admin_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (
    bucket_id = 'branding-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin'
);

-- =====================================================
-- 3. STORAGE POLICIES FOR PRIVATE BUCKETS
-- =====================================================

-- Attachments policies (staff can manage, clients can view their own)
CREATE POLICY "attachments_staff_all"
ON storage.objects FOR ALL
TO authenticated
USING (
    bucket_id = 'attachments' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') IN ('admin', 'vet', 'assistant', 'receptionist')
)
WITH CHECK (
    bucket_id = 'attachments' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') IN ('admin', 'vet', 'assistant', 'receptionist')
);

CREATE POLICY "attachments_client_read_own"
ON storage.objects FOR SELECT
TO authenticated
USING (
    bucket_id = 'attachments' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'client' AND
    (storage.foldername(name))[1] = auth.uid()::text
);

-- Patient images policies (staff can manage, clients can view their pets)
CREATE POLICY "patient_images_staff_all"
ON storage.objects FOR ALL
TO authenticated
USING (
    bucket_id = 'patient-images' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') IN ('admin', 'vet', 'assistant', 'receptionist')
)
WITH CHECK (
    bucket_id = 'patient-images' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') IN ('admin', 'vet', 'assistant', 'receptionist')
);

CREATE POLICY "patient_images_client_read_own"
ON storage.objects FOR SELECT
TO authenticated
USING (
    bucket_id = 'patient-images' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'client' AND
    EXISTS (
        SELECT 1 FROM patients p
        JOIN clients c ON p.client_id = c.id
        WHERE c.user_id = auth.uid()
        AND (storage.foldername(name))[1] = p.id::text
    )
);

-- =====================================================
-- 4. HELPER FUNCTIONS FOR STORAGE
-- =====================================================

-- Function to get file extension
CREATE OR REPLACE FUNCTION storage.extension(name text)
RETURNS text AS $
BEGIN
    RETURN lower(substring(name from '\.([^.]*)$'));
END;
$ LANGUAGE plpgsql;

-- Function to get folder name from path
CREATE OR REPLACE FUNCTION storage.foldername(name text)
RETURNS text[] AS $
BEGIN
    RETURN string_to_array(name, '/');
END;
$ LANGUAGE plpgsql;

-- =====================================================
-- 5. STORAGE VALIDATION FUNCTIONS
-- =====================================================

-- Function to validate image file types
CREATE OR REPLACE FUNCTION storage.is_image(name text)
RETURNS boolean AS $
BEGIN
    RETURN storage.extension(name) IN ('jpg', 'jpeg', 'png', 'webp', 'gif', 'svg');
END;
$ LANGUAGE plpgsql;

-- Function to validate file size (in bytes)
CREATE OR REPLACE FUNCTION storage.is_valid_size(size bigint, max_size bigint)
RETURNS boolean AS $
BEGIN
    RETURN size <= max_size;
END;
$ LANGUAGE plpgsql;

-- =====================================================
-- 6. ENHANCED STORAGE POLICIES WITH VALIDATION
-- =====================================================

-- Enhanced landing assets policy with file type validation
DROP POLICY IF EXISTS "landing_assets_admin_write" ON storage.objects;
CREATE POLICY "landing_assets_admin_write"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'landing-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin' AND
    storage.is_image(name) AND
    storage.is_valid_size(metadata->>'size'::bigint, 10485760)
);

-- Enhanced branding assets policy with file type validation
DROP POLICY IF EXISTS "branding_assets_admin_write" ON storage.objects;
CREATE POLICY "branding_assets_admin_write"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'branding-assets' AND 
    (auth.jwt() ->> 'user_metadata' ->> 'role') = 'admin' AND
    storage.is_image(name) AND
    storage.is_valid_size(metadata->>'size'::bigint, 5242880)
);

-- =====================================================
-- 7. STORAGE CLEANUP FUNCTIONS
-- =====================================================

-- Function to clean up orphaned files
CREATE OR REPLACE FUNCTION storage.cleanup_orphaned_files()
RETURNS void AS $
DECLARE
    orphaned_file RECORD;
BEGIN
    -- This is a placeholder for cleanup logic
    -- In practice, you'd identify files that are no longer referenced
    -- by any database records and remove them
    
    RAISE NOTICE 'Storage cleanup function created. Implement cleanup logic as needed.';
END;
$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- SUCCESS MESSAGE
-- =====================================================
DO $
BEGIN
    RAISE NOTICE '✅ Storage audit fixes applied successfully!';
    RAISE NOTICE '📁 Storage bucket policies configured';
    RAISE NOTICE '🔐 Role-based access control for files';
    RAISE NOTICE '✅ File type and size validation enabled';
    RAISE NOTICE '🧹 Cleanup functions available';
    RAISE NOTICE '';
    RAISE NOTICE '📝 MANUAL STEPS REQUIRED:';
    RAISE NOTICE '1. Create storage buckets in Supabase Dashboard if they don''t exist';
    RAISE NOTICE '2. Test file upload/download with different user roles';
    RAISE NOTICE '3. Configure CORS settings for public buckets if needed';
END $;